// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uekkdcsjyhfmcubgirtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVla2tkY3NqeWhmbWN1YmdpcnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NjMzOTgsImV4cCI6MjA1NDIzOTM5OH0.Nsow3D0eGnei64j7-S-2iksGQRoD6tmkbUt-DElo_bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);